
---
  - name: PLAY 1 - FACTS
    hosts: "iosxe"
    connection: network_cli
    gather_facts: no
    tasks:
        - name: First Task - Configure CDP and LLDP 
          ios_config:
            lines:
                - no cdp run
                - no lldp run

        - name: Second Task - Configure Interface 
          ios_config:
            lines:
                - "no interface Loopback1337"
                - "no interface Loopback124"
                - "no interface Loopback125"
                - "no interface Loopback1450"
                - "no ip access-list extended test"

